### ISSUE TITLE
Support custom Gradle test tasks

### ISSUE THREAD

**Issue by jorn86** [junit-team/junit5-samples#35]
I have a custom integration test task in my gradle build file:

```
task integrationTest(type:Test) {
	testClassesDir = sourceSets.integrationTest.output.classesDir
	classpath = sourceSets.integrationTest.runtimeClasspath
}
```

How do I configure it so that it will run JUnit 5 tests using the plugin?

**Comment by marcphilipp** [comment]
I'm afraid that's not possible right now. We were hoping the Gradle team would pick up https://github.com/gradle/gradle/issues/1037 sooner. Feel free to post there, maybe that will help to change their priorities. In the meantime, you can work around this limitation [using a custom task](https://stackoverflow.com/a/43512503/6327046).

I'm closing this task because junit5-samples is not the right repo to address this in.

**Comment by jorn86** [comment]
Thanks for the response, I solved my issue using your SO link.
I'll encourage the gradle team to speed up that issue too.
